services:
  - type: web
    name: ml-oauth-flask
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ML_CLIENT_ID
        value: "6426991503346208"
      - key: ML_CLIENT_SECRET
        value: "gJ5JzqdEIIQFmvRmaxozwaE7hrOFWhkE"
      - key: ML_REDIRECT_URI
        value: "https://ml-oauth-flask.onrender.com/callback"
